sudo: required

language: python
services:
  - docker

install:
  -  pip install python-coveralls

before_install:
  - deployment/build-server.sh .
  - deployment/run-server.sh
  - docker ps -a

script:
  - docker exec server-container pytest --cov-report term-missing --cov

after_success:
  - docker cp server-container:/32de-python/.coverage .coverage
  - coverage combine
  - coveralls

after_script:
  - docker rm -f server-container