sudo: required

language: python
python:
    - "3.6"
services:
  - docker

install:
  -  pip install python-coveralls
  -  pip list

before_install:
  - deployment/build-server.sh .
  - deployment/run-server.sh
  - docker ps -a

script:
  - docker exec server-container pytest --cov-report term-missing --cov=.

after_success:
  - docker cp server-container:/32de-python/.coverage .coverage.docker
  - cat .coverage.docker
  - cat .coveragerc
  - coverage report
  - coverage --version
  - coverage combine
  - cat .coverage
  - coveralls

after_script:
  - docker rm -f server-container