language: python

services:
  - docker

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - docker build -t server -f Dockerfile .
  - docker run -d --name app-container server
  - docker ps -a

script:
  - docker exec app-container pytest

after_script:
- docker rm -f app