sudo: required

language: python

+python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
+install:
  - pip install -r requirements.txt

before_install:
  - echo "deb http://downloads.skewed.de/apt/xenial xenial universe" | tee -a /etc/apt/sources.list
  - echo "deb-src http://downloads.skewed.de/apt/xenial xenial universe" | tee -a /etc/apt/sources.list
  - apt-get -qq update
  - apt-get install -y libboost-all-dev
  - apt-get install -y python3-graph-tool

script:
  - pytest --cov-report term-missing --cov

after_success:
  - coveralls