sudo: required

services:
  - docker

before_install:
  - docker build -t server -f Dockerfile .
  - docker run -d --name app-container server
  - docker ps -a

script:
  - docker exec app-container pytest

after_script:
- docker rm -f app