sudo: required

services:
  - docker

before_install:
  - docker build -t server -f Dockerfile .
  - docker run -d --name server-container server
  - docker ps -a

script:
  - docker exec server-container pytest

after_script:
  - docker rm -f server-container