FROM neo4j:3.3-enterprise
RUN apt-get update && apt-get install -y git maven
RUN git clone -b alpha-dev https://github.com/KDD-OpenSource/neo4j-graph-algorithms.git
WORKDIR neo4j-graph-algorithms
RUN mvn clean install
RUN cp algo/target/graph-algorithms-*.jar /plugins/