FROM neo4j:3.3-enterprise
RUN apk --update add git maven openjdk8
RUN git clone -b alpha-dev https://github.com/KDD-OpenSource/neo4j-graph-algorithms.git
WORKDIR neo4j-graph-algorithms
RUN mvn -Dmaven.test.skip=true clean install
RUN cp algo/target/graph-algorithms-*.jar /var/lib/neo4j/plugins/

# TODO: I think we would have to use the file from the neo4j repo
# ENTRYPOINT ["/docker-entrypoint.sh"]
# CMD ["neo4j console"]
ENTRYPOINT ["neo4j", "console"]