FROM server:latest

RUN apt-get update && apt-get install -y graphviz
RUN pip3 install jupyter

# Add Tini. Tini operates as a process subreaper for jupyter. This prevents
# kernel crashes.
ENV TINI_VERSION v0.6.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN chmod +x /usr/bin/tini
ENTRYPOINT ["/usr/bin/tini", "--"]

COPY . /32de-python/

EXPOSE 8888
CMD ["jupyter", "notebook", "--config", "deployment/jupyter_notebook_config.py"]
