# Based on Jupyter's Scipy-Notebook
# https://github.com/jupyter/docker-stacks/blob/master/scipy-notebook/Dockerfile
FROM jupyter/scipy-notebook

USER root

RUN conda install -c ostrokach-forge graph-tool --quiet --yes
RUN pip install graphviz

COPY requirements.txt /32de-python/
RUN pip install -r /32de-python/requirements.txt

USER $NB_UID